In [879]:
import pandas as pd
import numpy as np
df = pd.read_csv('listings 2.csv')
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 85 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   listing_url                                   453 non-null    object
 2   scrape_id                                     453 non-null    int64
 3   last_scraped                                  453 non-null    object
 4   source                                        453 non-null    object
 5   name                                          453 non-null    object
 6   description                                   442 non-null    object
 7   neighborhood_overview                         0 non-null      float64
 8   picture_url                                   453 non-null    object
 9   host_id                                       453 non-null    int64
 10  host_url                                      453 non-null    object
 11  host_profile_id                               453 non-null    int64
 12  host_profile_url                              453 non-null    object
 13  host_name                                     453 non-null    object
 14  host_since                                    0 non-null      float64
 15  hosts_time_as_user_years                      453 non-null    int64
 16  hosts_time_as_user_months                     453 non-null    int64
 17  hosts_time_as_host_years                      453 non-null    int64
 18  hosts_time_as_host_months                     453 non-null    int64
 19  host_location                                 333 non-null    object
 20  host_about                                    254 non-null    object
 21  host_response_time                            0 non-null      float64
 22  host_response_rate                            0 non-null      float64
 23  host_acceptance_rate                          0 non-null      float64
 24  host_is_superhost                             453 non-null    object
 25  host_thumbnail_url                            0 non-null      float64
 26  host_picture_url                              453 non-null    object
 27  host_neighbourhood                            0 non-null      float64
 28  host_listings_count                           453 non-null    int64
 29  host_total_listings_count                     0 non-null      float64
 30  host_verifications                            0 non-null      float64
 31  host_has_profile_pic                          453 non-null    object
 32  host_identity_verified                        453 non-null    object
 33  neighbourhood                                 0 non-null      float64
 34  neighbourhood_cleansed                        453 non-null    object
 35  neighbourhood_group_cleansed                  0 non-null      float64
 36  latitude                                      453 non-null    float64
 37  longitude                                     453 non-null    float64
 38  property_type                                 453 non-null    object
 39  room_type                                     453 non-null    object
 40  accommodates                                  453 non-null    int64
 41  bathrooms                                     437 non-null    float64
 42  bathrooms_text                                453 non-null    object
 43  bedrooms                                      450 non-null    float64
 44  beds                                          437 non-null    float64
 45  amenities                                     453 non-null    object
 46  price                                         0 non-null      float64
 47  minimum_nights                                453 non-null    int64
 48  maximum_nights                                453 non-null    int64
 49  minimum_minimum_nights                        453 non-null    int64
 50  maximum_minimum_nights                        453 non-null    int64
 51  minimum_maximum_nights                        453 non-null    int64
 52  maximum_maximum_nights                        453 non-null    int64
 53  minimum_nights_avg_ntm                        453 non-null    float64
 54  maximum_nights_avg_ntm                        453 non-null    float64
 55  calendar_updated                              0 non-null      float64
 56  has_availability                              448 non-null    object
 57  availability_30                               453 non-null    int64
 58  availability_60                               453 non-null    int64
 59  availability_90                               453 non-null    int64
 60  availability_365                              453 non-null    int64
 61  calendar_last_scraped                         453 non-null    object
 62  number_of_reviews                             453 non-null    int64
 63  number_of_reviews_ltm                         453 non-null    int64
 64  number_of_reviews_l30d                        453 non-null    int64
 65  availability_eoy                              453 non-null    int64
 66  number_of_reviews_ly                          453 non-null    int64
 67  estimated_occupancy_l365d                     453 non-null    int64
 68  estimated_revenue_l365d                       0 non-null      float64
 69  first_review                                  395 non-null    object
 70  last_review                                   395 non-null    object
 71  review_scores_rating                          395 non-null    float64
 72  review_scores_accuracy                        395 non-null    float64
 73  review_scores_cleanliness                     395 non-null    float64
 74  review_scores_checkin                         395 non-null    float64
 75  review_scores_communication                   395 non-null    float64
 76  review_scores_location                        395 non-null    float64
 77  review_scores_value                           395 non-null    float64
 78  license                                       0 non-null      float64
 79  instant_bookable                              0 non-null      float64
 80  calculated_host_listings_count                453 non-null    int64
 81  calculated_host_listings_count_entire_homes   453 non-null    int64
 82  calculated_host_listings_count_private_rooms  453 non-null    int64
 83  calculated_host_listings_count_shared_rooms   453 non-null    int64
 84  reviews_per_month                             395 non-null    float64
dtypes: float64(31), int64(30), object(24)
memory usage: 300.9+ KB

,id,scrape_id,neighborhood_overview,host_id,host_profile_id,host_since,hosts_time_as_user_years,hosts_time_as_user_months,hosts_time_as_host_years,hosts_time_as_host_months,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,4.530000e+02,4.530000e+02,0.0,4.530000e+02,4.530000e+02,0.0,453.000000,453.000000,453.000000,453.000000,...,395.000000,395.000000,395.000000,0.0,0.0,453.000000,453.000000,453.000000,453.0,395.000000
mean,8.981917e+17,2.026022e+13,NaN,2.505305e+08,1.468835e+18,NaN,6.741722,5.538631,4.139073,5.746137,...,4.838759,4.633924,4.692835,NaN,NaN,7.662252,5.743929,1.918322,0.0,1.840684
std,5.701275e+17,3.910569e-03,NaN,2.013526e+08,1.395864e+16,NaN,3.416767,3.291372,3.007453,3.409320,...,0.364384,0.451638,0.403480,NaN,NaN,7.994650,7.567732,3.860962,0.0,1.888654
min,2.992450e+06,2.026022e+13,NaN,6.490680e+05,1.462518e+18,NaN,0.000000,0.000000,0.000000,0.000000,...,1.000000,2.000000,2.500000,NaN,NaN,1.000000,0.000000,0.000000,0.0,0.030000
25%,5.932721e+17,2.026022e+13,NaN,4.762598e+07,1.463514e+18,NaN,4.000000,3.000000,2.000000,3.000000,...,4.840000,4.500000,4.630000,NaN,NaN,1.000000,1.000000,0.000000,0.0,0.425000
50%,1.020519e+18,2.026022e+13,NaN,2.329679e+08,1.468114e+18,NaN,7.000000,6.000000,4.000000,6.000000,...,4.950000,4.790000,4.810000,NaN,NaN,5.000000,2.000000,0.000000,0.0,1.230000
75%,1.383911e+18,2.026022e+13,NaN,4.330961e+08,1.469695e+18,NaN,10.000000,8.000000,6.000000,9.000000,...,5.000000,4.930000,4.930000,NaN,NaN,11.000000,7.000000,1.000000,0.0,2.575000
max,1.611096e+18,2.026022e+13,NaN,7.395856e+08,1.601568e+18,NaN,14.000000,11.000000,13.000000,11.000000,...,5.000000,5.000000,5.000000,NaN,NaN,30.000000,29.000000,13.000000,0.0,10.440000

In [880]:
df.shape

(453, 85)

In [881]:
df.isnull().sum().sort_values(ascending=False)
#Sum features have all values missing so these can be dropped

host_thumbnail_url           453
host_total_listings_count    453
host_response_time           453
host_response_rate           453
host_acceptance_rate         453
                            ...
amenities                      0
minimum_nights                 0
maximum_nights                 0
minimum_minimum_nights         0
bathrooms_text                 0
Length: 85, dtype: int64

In [882]:
df = df.drop(columns='host_thumbnail_url')

In [883]:
df = df.drop(columns=['host_total_listings_count','host_response_time','host_response_rate','host_acceptance_rate'])

In [884]:
df.isnull().sum().sort_values(ascending=False)[:20]
#Find out all columns which have no values. Drop them together

host_neighbourhood              453
calendar_updated                453
price                           453
neighbourhood_group_cleansed    453
neighbourhood                   453
host_verifications              453
neighborhood_overview           453
instant_bookable                453
license                         453
estimated_revenue_l365d         453
host_since                      453
host_about                      199
host_location                   120
review_scores_rating             58
first_review                     58
last_review                      58
reviews_per_month                58
review_scores_accuracy           58
review_scores_checkin            58
review_scores_communication      58
dtype: int64

In [885]:
df = df.drop(columns=['host_neighbourhood','calendar_updated','price','neighbourhood_group_cleansed','neighbourhood','host_verifications','neighborhood_overview','instant_bookable','license','estimated_revenue_l365d','host_since'])

In [886]:
df.isnull().sum().sort_values(ascending=False)[:20]
#Featues reduced. All columns with no values removed. Now fill rest of the empty values

host_about                     199
host_location                  120
review_scores_communication     58
first_review                    58
last_review                     58
review_scores_rating            58
review_scores_accuracy          58
review_scores_cleanliness       58
review_scores_checkin           58
reviews_per_month               58
review_scores_location          58
review_scores_value             58
beds                            16
bathrooms                       16
description                     11
has_availability                 5
bedrooms                         3
availability_365                 0
maximum_maximum_nights           0
minimum_nights_avg_ntm           0
dtype: int64

In [887]:
df[df['bedrooms'].isnull()]

,id,listing_url,scrape_id,last_scraped,source,name,description,picture_url,host_id,host_url,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
16,17238066,https://www.airbnb.com/rooms/17238066,20260215064701,2026-02-15,previous scrape,"$53($25 foreign student)Twin, noa/cno Smoke fr...",IF YOUR PRIORITY IS GOOD NEIGHBORHOOD AND FANC...,https://a0.muscache.com/pictures/4c939df7-1935...,61700428,https://www.airbnb.com/users/show/61700428,...,4.53,4.96,4.96,4.67,4.94,2,0,2,0,1.23
44,32279028,https://www.airbnb.com/rooms/32279028,20260215064701,2026-02-15,previous scrape,"Cosy, comfy and quiet for one",Comfortable single- family home in quiet resid...,https://a0.muscache.com/pictures/airflow/Hosti...,172223381,https://www.airbnb.com/users/show/172223381,...,4.98,4.98,4.99,4.97,4.97,2,0,2,0,2.58
294,1269145433396830936,https://www.airbnb.com/rooms/1269145433396830936,20260215064701,2026-02-15,previous scrape,King Bed in Spacious Aparment Close to Everything,"Welcome to our beautiful apartment, perfectly ...",https://a0.muscache.com/pictures/hosting/Hosti...,382970529,https://www.airbnb.com/users/show/382970529,...,4.83,4.67,4.33,4.83,4.33,17,4,13,0,0.38

In [888]:
#Too many columns give review. CHeck if they are correlated and drop unnecessary cols
review_cols = ['review_scores_accuracy','review_scores_cleanliness','review_scores_checkin','review_scores_location','review_scores_value','review_scores_communication']
df[review_cols].corr() > 0.8

#Correlation is low so we keep all. Create another column to find average ratings from these metrics. Check correlation with overall ratings
df['avg_rating_score'] = df[review_cols].mean(axis=1)
df['avg_rating_score'].isnull().sum()

df[['review_scores_rating','avg_rating_score']].corr()
#Correlation is high. So data is redundant. We can drop review_scores_rating and keep avg_rating_score as its calculation is transparent

                      review_scores_rating  avg_rating_score
review_scores_rating              1.000000          0.922895
avg_rating_score                  0.922895          1.000000

In [889]:
df = df.drop(columns='review_scores_rating')

In [890]:
df[df.duplicated()]
#No duplicate rows

Empty DataFrame
Columns: [id, listing_url, scrape_id, last_scraped, source, name, description, picture_url, host_id, host_url, host_profile_id, host_profile_url, host_name, hosts_time_as_user_years, hosts_time_as_user_months, hosts_time_as_host_years, hosts_time_as_host_months, host_location, host_about, host_is_superhost, host_picture_url, host_listings_count, host_has_profile_pic, host_identity_verified, neighbourhood_cleansed, latitude, longitude, property_type, room_type, accommodates, bathrooms, bathrooms_text, bedrooms, beds, amenities, minimum_nights, maximum_nights, minimum_minimum_nights, maximum_minimum_nights, minimum_maximum_nights, maximum_maximum_nights, minimum_nights_avg_ntm, maximum_nights_avg_ntm, has_availability, availability_30, availability_60, availability_90, availability_365, calendar_last_scraped, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, availability_eoy, number_of_reviews_ly, estimated_occupancy_l365d, first_review, last_review, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, avg_rating_score]
Index: []

[0 rows x 69 columns]

In [891]:
df.isnull().sum().sort_values(ascending=False)

host_about                199
host_location             120
review_scores_location     58
first_review               58
last_review                58
                         ...
accommodates                0
bathrooms_text              0
listing_url                 0
minimum_nights              0
amenities                   0
Length: 69, dtype: int64

In [892]:
df.loc[df['host_about']=="I grew up in Cebu, Philippines and moved to the Albany, NY area when I was ten years old. Since getting my Bachelor's in Computer Engineering from NYU Tandon, I've worked in video production, higher education, satellite engineering, crypto, and real estate. I love traveling on small budgets (with the help of award travel with credit card points and miles), and I have a passion for technology, real estate investment, and entrepreneurship.",'host_location'] = "Albany, NY"

In [893]:
df.loc[df['host_about']=="I'm Matt, your friendly host. While you’ll primarily communicate with me, the awesome team at Short & Comfy takes great care of the property so you may hear from them if needed. As a local here in the historic city of Albany, New York, I've developed a deep appreciation for the charm and character of the Capital Region and a knack for creating great guest experiences. Welcome to my Airbnb listing nestled in the heart of this vibrant community.",'host_location'] = "Albany, NY"

In [894]:
df.isnull().sum().sort_values(ascending=False)[:20]

host_about                     199
host_location                  107
review_scores_location          58
first_review                    58
last_review                     58
review_scores_accuracy          58
review_scores_cleanliness       58
review_scores_checkin           58
review_scores_communication     58
avg_rating_score                58
review_scores_value             58
reviews_per_month               58
beds                            16
bathrooms                       16
description                     11
has_availability                 5
bedrooms                         3
availability_365                 0
maximum_maximum_nights           0
minimum_nights_avg_ntm           0
dtype: int64

In [895]:
df['host_location'].fillna('Unknown',inplace=True)

/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/2746093069.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['host_location'].fillna('Unknown',inplace=True)

In [896]:
df.isnull().sum().sort_values(ascending=False)[:20]

host_about                     199
review_scores_location          58
first_review                    58
last_review                     58
review_scores_accuracy          58
review_scores_cleanliness       58
review_scores_checkin           58
review_scores_communication     58
avg_rating_score                58
review_scores_value             58
reviews_per_month               58
beds                            16
bathrooms                       16
description                     11
has_availability                 5
bedrooms                         3
availability_365                 0
minimum_maximum_nights           0
maximum_maximum_nights           0
minimum_nights_avg_ntm           0
dtype: int64

In [897]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 69 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   listing_url                                   453 non-null    object
 2   scrape_id                                     453 non-null    int64
 3   last_scraped                                  453 non-null    object
 4   source                                        453 non-null    object
 5   name                                          453 non-null    object
 6   description                                   442 non-null    object
 7   picture_url                                   453 non-null    object
 8   host_id                                       453 non-null    int64
 9   host_url                                      453 non-null    object
 10  host_profile_id                               453 non-null    int64
 11  host_profile_url                              453 non-null    object
 12  host_name                                     453 non-null    object
 13  hosts_time_as_user_years                      453 non-null    int64
 14  hosts_time_as_user_months                     453 non-null    int64
 15  hosts_time_as_host_years                      453 non-null    int64
 16  hosts_time_as_host_months                     453 non-null    int64
 17  host_location                                 453 non-null    object
 18  host_about                                    254 non-null    object
 19  host_is_superhost                             453 non-null    object
 20  host_picture_url                              453 non-null    object
 21  host_listings_count                           453 non-null    int64
 22  host_has_profile_pic                          453 non-null    object
 23  host_identity_verified                        453 non-null    object
 24  neighbourhood_cleansed                        453 non-null    object
 25  latitude                                      453 non-null    float64
 26  longitude                                     453 non-null    float64
 27  property_type                                 453 non-null    object
 28  room_type                                     453 non-null    object
 29  accommodates                                  453 non-null    int64
 30  bathrooms                                     437 non-null    float64
 31  bathrooms_text                                453 non-null    object
 32  bedrooms                                      450 non-null    float64
 33  beds                                          437 non-null    float64
 34  amenities                                     453 non-null    object
 35  minimum_nights                                453 non-null    int64
 36  maximum_nights                                453 non-null    int64
 37  minimum_minimum_nights                        453 non-null    int64
 38  maximum_minimum_nights                        453 non-null    int64
 39  minimum_maximum_nights                        453 non-null    int64
 40  maximum_maximum_nights                        453 non-null    int64
 41  minimum_nights_avg_ntm                        453 non-null    float64
 42  maximum_nights_avg_ntm                        453 non-null    float64
 43  has_availability                              448 non-null    object
 44  availability_30                               453 non-null    int64
 45  availability_60                               453 non-null    int64
 46  availability_90                               453 non-null    int64
 47  availability_365                              453 non-null    int64
 48  calendar_last_scraped                         453 non-null    object
 49  number_of_reviews                             453 non-null    int64
 50  number_of_reviews_ltm                         453 non-null    int64
 51  number_of_reviews_l30d                        453 non-null    int64
 52  availability_eoy                              453 non-null    int64
 53  number_of_reviews_ly                          453 non-null    int64
 54  estimated_occupancy_l365d                     453 non-null    int64
 55  first_review                                  395 non-null    object
 56  last_review                                   395 non-null    object
 57  review_scores_accuracy                        395 non-null    float64
 58  review_scores_cleanliness                     395 non-null    float64
 59  review_scores_checkin                         395 non-null    float64
 60  review_scores_communication                   395 non-null    float64
 61  review_scores_location                        395 non-null    float64
 62  review_scores_value                           395 non-null    float64
 63  calculated_host_listings_count                453 non-null    int64
 64  calculated_host_listings_count_entire_homes   453 non-null    int64
 65  calculated_host_listings_count_private_rooms  453 non-null    int64
 66  calculated_host_listings_count_shared_rooms   453 non-null    int64
 67  reviews_per_month                             395 non-null    float64
 68  avg_rating_score                              395 non-null    float64
dtypes: float64(15), int64(30), object(24)
memory usage: 244.3+ KB

In [898]:
df['scrape_id'].duplicated().count()
#All duplicated values. Column can be dropped
df = df.drop(columns=['host_about','scrape_id','listing_url','picture_url','host_url','host_profile_id','host_profile_url','host_about'])

In [899]:

df['host_has_profile_pic'].value_counts()
#little variation - can be dropped

host_has_profile_pic
t    440
f     13
Name: count, dtype: int64

In [900]:
df = df.drop(columns='host_has_profile_pic')

In [901]:
df.info()
df['hosts_time_as_host_total_years'] = (df['hosts_time_as_host_years'] + df['hosts_time_as_host_months']/12)
df['hosts_time_as_user_total_years'] = (df['hosts_time_as_user_years'] + df['hosts_time_as_user_months']/12)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 61 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   last_scraped                                  453 non-null    object
 2   source                                        453 non-null    object
 3   name                                          453 non-null    object
 4   description                                   442 non-null    object
 5   host_id                                       453 non-null    int64
 6   host_name                                     453 non-null    object
 7   hosts_time_as_user_years                      453 non-null    int64
 8   hosts_time_as_user_months                     453 non-null    int64
 9   hosts_time_as_host_years                      453 non-null    int64
 10  hosts_time_as_host_months                     453 non-null    int64
 11  host_location                                 453 non-null    object
 12  host_is_superhost                             453 non-null    object
 13  host_picture_url                              453 non-null    object
 14  host_listings_count                           453 non-null    int64
 15  host_identity_verified                        453 non-null    object
 16  neighbourhood_cleansed                        453 non-null    object
 17  latitude                                      453 non-null    float64
 18  longitude                                     453 non-null    float64
 19  property_type                                 453 non-null    object
 20  room_type                                     453 non-null    object
 21  accommodates                                  453 non-null    int64
 22  bathrooms                                     437 non-null    float64
 23  bathrooms_text                                453 non-null    object
 24  bedrooms                                      450 non-null    float64
 25  beds                                          437 non-null    float64
 26  amenities                                     453 non-null    object
 27  minimum_nights                                453 non-null    int64
 28  maximum_nights                                453 non-null    int64
 29  minimum_minimum_nights                        453 non-null    int64
 30  maximum_minimum_nights                        453 non-null    int64
 31  minimum_maximum_nights                        453 non-null    int64
 32  maximum_maximum_nights                        453 non-null    int64
 33  minimum_nights_avg_ntm                        453 non-null    float64
 34  maximum_nights_avg_ntm                        453 non-null    float64
 35  has_availability                              448 non-null    object
 36  availability_30                               453 non-null    int64
 37  availability_60                               453 non-null    int64
 38  availability_90                               453 non-null    int64
 39  availability_365                              453 non-null    int64
 40  calendar_last_scraped                         453 non-null    object
 41  number_of_reviews                             453 non-null    int64
 42  number_of_reviews_ltm                         453 non-null    int64
 43  number_of_reviews_l30d                        453 non-null    int64
 44  availability_eoy                              453 non-null    int64
 45  number_of_reviews_ly                          453 non-null    int64
 46  estimated_occupancy_l365d                     453 non-null    int64
 47  first_review                                  395 non-null    object
 48  last_review                                   395 non-null    object
 49  review_scores_accuracy                        395 non-null    float64
 50  review_scores_cleanliness                     395 non-null    float64
 51  review_scores_checkin                         395 non-null    float64
 52  review_scores_communication                   395 non-null    float64
 53  review_scores_location                        395 non-null    float64
 54  review_scores_value                           395 non-null    float64
 55  calculated_host_listings_count                453 non-null    int64
 56  calculated_host_listings_count_entire_homes   453 non-null    int64
 57  calculated_host_listings_count_private_rooms  453 non-null    int64
 58  calculated_host_listings_count_shared_rooms   453 non-null    int64
 59  reviews_per_month                             395 non-null    float64
 60  avg_rating_score                              395 non-null    float64
dtypes: float64(15), int64(28), object(18)
memory usage: 216.0+ KB

In [902]:
df = df.drop(columns=['hosts_time_as_user_years','hosts_time_as_user_months','hosts_time_as_host_years','hosts_time_as_host_months'])

In [903]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 59 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   last_scraped                                  453 non-null    object
 2   source                                        453 non-null    object
 3   name                                          453 non-null    object
 4   description                                   442 non-null    object
 5   host_id                                       453 non-null    int64
 6   host_name                                     453 non-null    object
 7   host_location                                 453 non-null    object
 8   host_is_superhost                             453 non-null    object
 9   host_picture_url                              453 non-null    object
 10  host_listings_count                           453 non-null    int64
 11  host_identity_verified                        453 non-null    object
 12  neighbourhood_cleansed                        453 non-null    object
 13  latitude                                      453 non-null    float64
 14  longitude                                     453 non-null    float64
 15  property_type                                 453 non-null    object
 16  room_type                                     453 non-null    object
 17  accommodates                                  453 non-null    int64
 18  bathrooms                                     437 non-null    float64
 19  bathrooms_text                                453 non-null    object
 20  bedrooms                                      450 non-null    float64
 21  beds                                          437 non-null    float64
 22  amenities                                     453 non-null    object
 23  minimum_nights                                453 non-null    int64
 24  maximum_nights                                453 non-null    int64
 25  minimum_minimum_nights                        453 non-null    int64
 26  maximum_minimum_nights                        453 non-null    int64
 27  minimum_maximum_nights                        453 non-null    int64
 28  maximum_maximum_nights                        453 non-null    int64
 29  minimum_nights_avg_ntm                        453 non-null    float64
 30  maximum_nights_avg_ntm                        453 non-null    float64
 31  has_availability                              448 non-null    object
 32  availability_30                               453 non-null    int64
 33  availability_60                               453 non-null    int64
 34  availability_90                               453 non-null    int64
 35  availability_365                              453 non-null    int64
 36  calendar_last_scraped                         453 non-null    object
 37  number_of_reviews                             453 non-null    int64
 38  number_of_reviews_ltm                         453 non-null    int64
 39  number_of_reviews_l30d                        453 non-null    int64
 40  availability_eoy                              453 non-null    int64
 41  number_of_reviews_ly                          453 non-null    int64
 42  estimated_occupancy_l365d                     453 non-null    int64
 43  first_review                                  395 non-null    object
 44  last_review                                   395 non-null    object
 45  review_scores_accuracy                        395 non-null    float64
 46  review_scores_cleanliness                     395 non-null    float64
 47  review_scores_checkin                         395 non-null    float64
 48  review_scores_communication                   395 non-null    float64
 49  review_scores_location                        395 non-null    float64
 50  review_scores_value                           395 non-null    float64
 51  calculated_host_listings_count                453 non-null    int64
 52  calculated_host_listings_count_entire_homes   453 non-null    int64
 53  calculated_host_listings_count_private_rooms  453 non-null    int64
 54  calculated_host_listings_count_shared_rooms   453 non-null    int64
 55  reviews_per_month                             395 non-null    float64
 56  avg_rating_score                              395 non-null    float64
 57  hosts_time_as_host_total_years                453 non-null    float64
 58  hosts_time_as_user_total_years                453 non-null    float64
dtypes: float64(17), int64(24), object(18)
memory usage: 208.9+ KB

In [904]:
df['bathrooms_shared'] = df['bathrooms_text'].str.contains('shared',case=False).astype(int)
df['bathrooms'] = df['bathrooms_text'].str.extract(r'(\d+\.?\d*)').astype(float)

In [905]:
df = df.drop(columns='bathrooms_text')

In [906]:
df.isnull().sum().sort_values(ascending=False)[:20]
df['bathrooms'].fillna(0.5,inplace=True)

/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3936180113.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['bathrooms'].fillna(0.5,inplace=True)

In [907]:
df.isnull().sum().sort_values(ascending=False)[:20]

review_scores_cleanliness         58
review_scores_location            58
first_review                      58
avg_rating_score                  58
reviews_per_month                 58
last_review                       58
review_scores_accuracy            58
review_scores_checkin             58
review_scores_communication       58
review_scores_value               58
beds                              16
description                       11
has_availability                   5
bedrooms                           3
calculated_host_listings_count     0
availability_eoy                   0
availability_90                    0
availability_365                   0
calendar_last_scraped              0
number_of_reviews                  0
dtype: int64

In [908]:
df = df.drop(columns=['minimum_minimum_nights','maximum_minimum_nights','maximum_maximum_nights','minimum_maximum_nights'])

In [909]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 55 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   last_scraped                                  453 non-null    object
 2   source                                        453 non-null    object
 3   name                                          453 non-null    object
 4   description                                   442 non-null    object
 5   host_id                                       453 non-null    int64
 6   host_name                                     453 non-null    object
 7   host_location                                 453 non-null    object
 8   host_is_superhost                             453 non-null    object
 9   host_picture_url                              453 non-null    object
 10  host_listings_count                           453 non-null    int64
 11  host_identity_verified                        453 non-null    object
 12  neighbourhood_cleansed                        453 non-null    object
 13  latitude                                      453 non-null    float64
 14  longitude                                     453 non-null    float64
 15  property_type                                 453 non-null    object
 16  room_type                                     453 non-null    object
 17  accommodates                                  453 non-null    int64
 18  bathrooms                                     453 non-null    float64
 19  bedrooms                                      450 non-null    float64
 20  beds                                          437 non-null    float64
 21  amenities                                     453 non-null    object
 22  minimum_nights                                453 non-null    int64
 23  maximum_nights                                453 non-null    int64
 24  minimum_nights_avg_ntm                        453 non-null    float64
 25  maximum_nights_avg_ntm                        453 non-null    float64
 26  has_availability                              448 non-null    object
 27  availability_30                               453 non-null    int64
 28  availability_60                               453 non-null    int64
 29  availability_90                               453 non-null    int64
 30  availability_365                              453 non-null    int64
 31  calendar_last_scraped                         453 non-null    object
 32  number_of_reviews                             453 non-null    int64
 33  number_of_reviews_ltm                         453 non-null    int64
 34  number_of_reviews_l30d                        453 non-null    int64
 35  availability_eoy                              453 non-null    int64
 36  number_of_reviews_ly                          453 non-null    int64
 37  estimated_occupancy_l365d                     453 non-null    int64
 38  first_review                                  395 non-null    object
 39  last_review                                   395 non-null    object
 40  review_scores_accuracy                        395 non-null    float64
 41  review_scores_cleanliness                     395 non-null    float64
 42  review_scores_checkin                         395 non-null    float64
 43  review_scores_communication                   395 non-null    float64
 44  review_scores_location                        395 non-null    float64
 45  review_scores_value                           395 non-null    float64
 46  calculated_host_listings_count                453 non-null    int64
 47  calculated_host_listings_count_entire_homes   453 non-null    int64
 48  calculated_host_listings_count_private_rooms  453 non-null    int64
 49  calculated_host_listings_count_shared_rooms   453 non-null    int64
 50  reviews_per_month                             395 non-null    float64
 51  avg_rating_score                              395 non-null    float64
 52  hosts_time_as_host_total_years                453 non-null    float64
 53  hosts_time_as_user_total_years                453 non-null    float64
 54  bathrooms_shared                              453 non-null    int64
dtypes: float64(17), int64(21), object(17)
memory usage: 194.8+ KB

In [910]:
df = df.drop(columns='host_picture_url')

In [911]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 54 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   last_scraped                                  453 non-null    object
 2   source                                        453 non-null    object
 3   name                                          453 non-null    object
 4   description                                   442 non-null    object
 5   host_id                                       453 non-null    int64
 6   host_name                                     453 non-null    object
 7   host_location                                 453 non-null    object
 8   host_is_superhost                             453 non-null    object
 9   host_listings_count                           453 non-null    int64
 10  host_identity_verified                        453 non-null    object
 11  neighbourhood_cleansed                        453 non-null    object
 12  latitude                                      453 non-null    float64
 13  longitude                                     453 non-null    float64
 14  property_type                                 453 non-null    object
 15  room_type                                     453 non-null    object
 16  accommodates                                  453 non-null    int64
 17  bathrooms                                     453 non-null    float64
 18  bedrooms                                      450 non-null    float64
 19  beds                                          437 non-null    float64
 20  amenities                                     453 non-null    object
 21  minimum_nights                                453 non-null    int64
 22  maximum_nights                                453 non-null    int64
 23  minimum_nights_avg_ntm                        453 non-null    float64
 24  maximum_nights_avg_ntm                        453 non-null    float64
 25  has_availability                              448 non-null    object
 26  availability_30                               453 non-null    int64
 27  availability_60                               453 non-null    int64
 28  availability_90                               453 non-null    int64
 29  availability_365                              453 non-null    int64
 30  calendar_last_scraped                         453 non-null    object
 31  number_of_reviews                             453 non-null    int64
 32  number_of_reviews_ltm                         453 non-null    int64
 33  number_of_reviews_l30d                        453 non-null    int64
 34  availability_eoy                              453 non-null    int64
 35  number_of_reviews_ly                          453 non-null    int64
 36  estimated_occupancy_l365d                     453 non-null    int64
 37  first_review                                  395 non-null    object
 38  last_review                                   395 non-null    object
 39  review_scores_accuracy                        395 non-null    float64
 40  review_scores_cleanliness                     395 non-null    float64
 41  review_scores_checkin                         395 non-null    float64
 42  review_scores_communication                   395 non-null    float64
 43  review_scores_location                        395 non-null    float64
 44  review_scores_value                           395 non-null    float64
 45  calculated_host_listings_count                453 non-null    int64
 46  calculated_host_listings_count_entire_homes   453 non-null    int64
 47  calculated_host_listings_count_private_rooms  453 non-null    int64
 48  calculated_host_listings_count_shared_rooms   453 non-null    int64
 49  reviews_per_month                             395 non-null    float64
 50  avg_rating_score                              395 non-null    float64
 51  hosts_time_as_host_total_years                453 non-null    float64
 52  hosts_time_as_user_total_years                453 non-null    float64
 53  bathrooms_shared                              453 non-null    int64
dtypes: float64(17), int64(21), object(16)
memory usage: 191.2+ KB

In [912]:
df[['beds','bedrooms','accommodates']].corr()
#High correlation so beds can use regression imputer
#bedrooms has only three missing values - so we can drop them
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression
it_imputer = IterativeImputer(estimator=LinearRegression())
cols = ['beds','bedrooms','accommodates']
df[cols] = it_imputer.fit_transform(df[cols])
df['beds'] = df['beds'].round()

In [913]:
df.isnull().sum().sort_values(ascending=False)[:20]

review_scores_checkin          58
review_scores_value            58
last_review                    58
review_scores_accuracy         58
review_scores_cleanliness      58
review_scores_communication    58
review_scores_location         58
first_review                   58
reviews_per_month              58
avg_rating_score               58
description                    11
has_availability                5
number_of_reviews_ltm           0
estimated_occupancy_l365d       0
availability_eoy                0
number_of_reviews               0
number_of_reviews_ly            0
calendar_last_scraped           0
number_of_reviews_l30d          0
id                              0
dtype: int64

In [914]:
df['has_availability'].duplicated().count()
#All values same.

np.int64(453)

In [915]:
df = df.drop(columns=['has_availability','availability_30','availability_60','availability_90'])

In [916]:
df = df.drop(columns=['maximum_nights_avg_ntm','minimum_nights_avg_ntm'])

In [917]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   last_scraped                                  453 non-null    object
 2   source                                        453 non-null    object
 3   name                                          453 non-null    object
 4   description                                   442 non-null    object
 5   host_id                                       453 non-null    int64
 6   host_name                                     453 non-null    object
 7   host_location                                 453 non-null    object
 8   host_is_superhost                             453 non-null    object
 9   host_listings_count                           453 non-null    int64
 10  host_identity_verified                        453 non-null    object
 11  neighbourhood_cleansed                        453 non-null    object
 12  latitude                                      453 non-null    float64
 13  longitude                                     453 non-null    float64
 14  property_type                                 453 non-null    object
 15  room_type                                     453 non-null    object
 16  accommodates                                  453 non-null    float64
 17  bathrooms                                     453 non-null    float64
 18  bedrooms                                      453 non-null    float64
 19  beds                                          453 non-null    float64
 20  amenities                                     453 non-null    object
 21  minimum_nights                                453 non-null    int64
 22  maximum_nights                                453 non-null    int64
 23  availability_365                              453 non-null    int64
 24  calendar_last_scraped                         453 non-null    object
 25  number_of_reviews                             453 non-null    int64
 26  number_of_reviews_ltm                         453 non-null    int64
 27  number_of_reviews_l30d                        453 non-null    int64
 28  availability_eoy                              453 non-null    int64
 29  number_of_reviews_ly                          453 non-null    int64
 30  estimated_occupancy_l365d                     453 non-null    int64
 31  first_review                                  395 non-null    object
 32  last_review                                   395 non-null    object
 33  review_scores_accuracy                        395 non-null    float64
 34  review_scores_cleanliness                     395 non-null    float64
 35  review_scores_checkin                         395 non-null    float64
 36  review_scores_communication                   395 non-null    float64
 37  review_scores_location                        395 non-null    float64
 38  review_scores_value                           395 non-null    float64
 39  calculated_host_listings_count                453 non-null    int64
 40  calculated_host_listings_count_entire_homes   453 non-null    int64
 41  calculated_host_listings_count_private_rooms  453 non-null    int64
 42  calculated_host_listings_count_shared_rooms   453 non-null    int64
 43  reviews_per_month                             395 non-null    float64
 44  avg_rating_score                              395 non-null    float64
 45  hosts_time_as_host_total_years                453 non-null    float64
 46  hosts_time_as_user_total_years                453 non-null    float64
 47  bathrooms_shared                              453 non-null    int64
dtypes: float64(16), int64(17), object(15)
memory usage: 170.0+ KB

In [918]:
df['calculated_host_listings_count'].equals(df['calculated_host_listings_count_entire_homes']+df['calculated_host_listings_count_private_rooms']+df['calculated_host_listings_count_shared_rooms'])

True

In [919]:
df.isnull().sum()

id                                               0
last_scraped                                     0
source                                           0
name                                             0
description                                     11
host_id                                          0
host_name                                        0
host_location                                    0
host_is_superhost                                0
host_listings_count                              0
host_identity_verified                           0
neighbourhood_cleansed                           0
latitude                                         0
longitude                                        0
property_type                                    0
room_type                                        0
accommodates                                     0
bathrooms                                        0
bedrooms                                         0
beds                                             0
amenities                                        0
minimum_nights                                   0
maximum_nights                                   0
availability_365                                 0
calendar_last_scraped                            0
number_of_reviews                                0
number_of_reviews_ltm                            0
number_of_reviews_l30d                           0
availability_eoy                                 0
number_of_reviews_ly                             0
estimated_occupancy_l365d                        0
first_review                                    58
last_review                                     58
review_scores_accuracy                          58
review_scores_cleanliness                       58
review_scores_checkin                           58
review_scores_communication                     58
review_scores_location                          58
review_scores_value                             58
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
calculated_host_listings_count_private_rooms     0
calculated_host_listings_count_shared_rooms      0
reviews_per_month                               58
avg_rating_score                                58
hosts_time_as_host_total_years                   0
hosts_time_as_user_total_years                   0
bathrooms_shared                                 0
dtype: int64

In [920]:
df.isnull().sum()

id                                               0
last_scraped                                     0
source                                           0
name                                             0
description                                     11
host_id                                          0
host_name                                        0
host_location                                    0
host_is_superhost                                0
host_listings_count                              0
host_identity_verified                           0
neighbourhood_cleansed                           0
latitude                                         0
longitude                                        0
property_type                                    0
room_type                                        0
accommodates                                     0
bathrooms                                        0
bedrooms                                         0
beds                                             0
amenities                                        0
minimum_nights                                   0
maximum_nights                                   0
availability_365                                 0
calendar_last_scraped                            0
number_of_reviews                                0
number_of_reviews_ltm                            0
number_of_reviews_l30d                           0
availability_eoy                                 0
number_of_reviews_ly                             0
estimated_occupancy_l365d                        0
first_review                                    58
last_review                                     58
review_scores_accuracy                          58
review_scores_cleanliness                       58
review_scores_checkin                           58
review_scores_communication                     58
review_scores_location                          58
review_scores_value                             58
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
calculated_host_listings_count_private_rooms     0
calculated_host_listings_count_shared_rooms      0
reviews_per_month                               58
avg_rating_score                                58
hosts_time_as_host_total_years                   0
hosts_time_as_user_total_years                   0
bathrooms_shared                                 0
dtype: int64

In [921]:
df['description'] = df['description'].fillna(df['name'])

In [922]:
df.isnull().sum()

id                                               0
last_scraped                                     0
source                                           0
name                                             0
description                                      0
host_id                                          0
host_name                                        0
host_location                                    0
host_is_superhost                                0
host_listings_count                              0
host_identity_verified                           0
neighbourhood_cleansed                           0
latitude                                         0
longitude                                        0
property_type                                    0
room_type                                        0
accommodates                                     0
bathrooms                                        0
bedrooms                                         0
beds                                             0
amenities                                        0
minimum_nights                                   0
maximum_nights                                   0
availability_365                                 0
calendar_last_scraped                            0
number_of_reviews                                0
number_of_reviews_ltm                            0
number_of_reviews_l30d                           0
availability_eoy                                 0
number_of_reviews_ly                             0
estimated_occupancy_l365d                        0
first_review                                    58
last_review                                     58
review_scores_accuracy                          58
review_scores_cleanliness                       58
review_scores_checkin                           58
review_scores_communication                     58
review_scores_location                          58
review_scores_value                             58
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
calculated_host_listings_count_private_rooms     0
calculated_host_listings_count_shared_rooms      0
reviews_per_month                               58
avg_rating_score                                58
hosts_time_as_host_total_years                   0
hosts_time_as_user_total_years                   0
bathrooms_shared                                 0
dtype: int64

In [923]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 453 entries, 0 to 452
Data columns (total 48 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            453 non-null    int64
 1   last_scraped                                  453 non-null    object
 2   source                                        453 non-null    object
 3   name                                          453 non-null    object
 4   description                                   453 non-null    object
 5   host_id                                       453 non-null    int64
 6   host_name                                     453 non-null    object
 7   host_location                                 453 non-null    object
 8   host_is_superhost                             453 non-null    object
 9   host_listings_count                           453 non-null    int64
 10  host_identity_verified                        453 non-null    object
 11  neighbourhood_cleansed                        453 non-null    object
 12  latitude                                      453 non-null    float64
 13  longitude                                     453 non-null    float64
 14  property_type                                 453 non-null    object
 15  room_type                                     453 non-null    object
 16  accommodates                                  453 non-null    float64
 17  bathrooms                                     453 non-null    float64
 18  bedrooms                                      453 non-null    float64
 19  beds                                          453 non-null    float64
 20  amenities                                     453 non-null    object
 21  minimum_nights                                453 non-null    int64
 22  maximum_nights                                453 non-null    int64
 23  availability_365                              453 non-null    int64
 24  calendar_last_scraped                         453 non-null    object
 25  number_of_reviews                             453 non-null    int64
 26  number_of_reviews_ltm                         453 non-null    int64
 27  number_of_reviews_l30d                        453 non-null    int64
 28  availability_eoy                              453 non-null    int64
 29  number_of_reviews_ly                          453 non-null    int64
 30  estimated_occupancy_l365d                     453 non-null    int64
 31  first_review                                  395 non-null    object
 32  last_review                                   395 non-null    object
 33  review_scores_accuracy                        395 non-null    float64
 34  review_scores_cleanliness                     395 non-null    float64
 35  review_scores_checkin                         395 non-null    float64
 36  review_scores_communication                   395 non-null    float64
 37  review_scores_location                        395 non-null    float64
 38  review_scores_value                           395 non-null    float64
 39  calculated_host_listings_count                453 non-null    int64
 40  calculated_host_listings_count_entire_homes   453 non-null    int64
 41  calculated_host_listings_count_private_rooms  453 non-null    int64
 42  calculated_host_listings_count_shared_rooms   453 non-null    int64
 43  reviews_per_month                             395 non-null    float64
 44  avg_rating_score                              395 non-null    float64
 45  hosts_time_as_host_total_years                453 non-null    float64
 46  hosts_time_as_user_total_years                453 non-null    float64
 47  bathrooms_shared                              453 non-null    int64
dtypes: float64(16), int64(17), object(15)
memory usage: 170.0+ KB

In [924]:
df = df.drop(columns='availability_eoy')

In [925]:
df[df['host_identity_verified']=='f']

,id,last_scraped,source,name,description,host_id,host_name,host_location,host_is_superhost,host_listings_count,...,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,avg_rating_score,hosts_time_as_host_total_years,hosts_time_as_user_total_years,bathrooms_shared
202,950613505102507073,2026-02-15,city scrape,Modern and cozy home,Your family will be close to everything when y...,529844022,Eraj,"Albany, NY",t,1,...,4.86,1,1,0,0,3.68,4.916667,2.500000,2.500000,0
232,1056469473906808728,2026-02-15,city scrape,"Bonjour, Bienvenue A Chez Pierre","Bonjour, Bienvenue A Chez Pierre",553112010,Lynn,Unknown,f,1,...,5.00,1,0,1,0,0.06,5.000000,2.083333,2.083333,1
395,1486971933919777260,2026-02-15,city scrape,Budget Friendly 2 BDRM with Modern Amenities W...,✔ 2 Bedrooms with TVs in each room!<br />✔ Lie...,65282034,Michael,Unknown,f,26,...,4.75,2,2,0,0,2.65,4.770000,3.166667,9.833333,0
423,1539837082076857746,2026-02-15,city scrape,Budget Friendly 5 BEDS with Modern Amenities W...,✔ 2 Bedrooms with 5 beds! TVs in each room!<b...,65282034,Michael,Unknown,f,26,...,3.75,2,2,0,0,1.11,4.125000,3.166667,9.833333,0

In [926]:
df.isnull().sum().sort_values(ascending=False)

review_scores_location                          58
review_scores_cleanliness                       58
avg_rating_score                                58
reviews_per_month                               58
first_review                                    58
last_review                                     58
review_scores_value                             58
review_scores_accuracy                          58
review_scores_communication                     58
review_scores_checkin                           58
number_of_reviews_ltm                            0
number_of_reviews_l30d                           0
number_of_reviews_ly                             0
estimated_occupancy_l365d                        0
id                                               0
calendar_last_scraped                            0
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
calculated_host_listings_count_private_rooms     0
calculated_host_listings_count_shared_rooms      0
hosts_time_as_host_total_years                   0
hosts_time_as_user_total_years                   0
number_of_reviews                                0
availability_365                                 0
last_scraped                                     0
neighbourhood_cleansed                           0
source                                           0
name                                             0
description                                      0
host_id                                          0
host_name                                        0
host_location                                    0
host_is_superhost                                0
host_listings_count                              0
host_identity_verified                           0
latitude                                         0
maximum_nights                                   0
longitude                                        0
property_type                                    0
room_type                                        0
accommodates                                     0
bathrooms                                        0
bedrooms                                         0
beds                                             0
amenities                                        0
minimum_nights                                   0
bathrooms_shared                                 0
dtype: int64

In [927]:
df.duplicated().sum()

np.int64(0)

In [928]:
df[df['review_scores_accuracy'] == 0]
#No scores are 0
# We can fill the missing values with 0, which signifies property is unreviewed

Empty DataFrame
Columns: [id, last_scraped, source, name, description, host_id, host_name, host_location, host_is_superhost, host_listings_count, host_identity_verified, neighbourhood_cleansed, latitude, longitude, property_type, room_type, accommodates, bathrooms, bedrooms, beds, amenities, minimum_nights, maximum_nights, availability_365, calendar_last_scraped, number_of_reviews, number_of_reviews_ltm, number_of_reviews_l30d, number_of_reviews_ly, estimated_occupancy_l365d, first_review, last_review, review_scores_accuracy, review_scores_cleanliness, review_scores_checkin, review_scores_communication, review_scores_location, review_scores_value, calculated_host_listings_count, calculated_host_listings_count_entire_homes, calculated_host_listings_count_private_rooms, calculated_host_listings_count_shared_rooms, reviews_per_month, avg_rating_score, hosts_time_as_host_total_years, hosts_time_as_user_total_years, bathrooms_shared]
Index: []

[0 rows x 47 columns]

In [929]:
df['review_scores_accuracy'].fillna(np.nan,inplace=True)
df['review_scores_cleanliness'].fillna(np.nan,inplace=True)
df['review_scores_value'].fillna(np.nan,inplace=True)
df['review_scores_communication'].fillna(np.nan,inplace=True)
df['review_scores_checkin'].fillna(np.nan,inplace=True)
df['review_scores_location'].fillna(np.nan,inplace=True)
df['reviews_per_month'].fillna(np.nan,inplace=True)
df['avg_rating_score'].fillna(np.nan,inplace=True)

/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores_accuracy'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores_cleanliness'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores_value'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores_communication'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores_checkin'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['review_scores_location'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reviews_per_month'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3431804283.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['avg_rating_score'].fillna(np.nan,inplace=True)

In [930]:
df['first_review'].fillna(np.nan,inplace=True)
df['last_review'].fillna(np.nan,inplace=True)

/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/545022706.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['first_review'].fillna(np.nan,inplace=True)
/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/545022706.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['last_review'].fillna(np.nan,inplace=True)

In [931]:
df.isnull().sum()

id                                               0
last_scraped                                     0
source                                           0
name                                             0
description                                      0
host_id                                          0
host_name                                        0
host_location                                    0
host_is_superhost                                0
host_listings_count                              0
host_identity_verified                           0
neighbourhood_cleansed                           0
latitude                                         0
longitude                                        0
property_type                                    0
room_type                                        0
accommodates                                     0
bathrooms                                        0
bedrooms                                         0
beds                                             0
amenities                                        0
minimum_nights                                   0
maximum_nights                                   0
availability_365                                 0
calendar_last_scraped                            0
number_of_reviews                                0
number_of_reviews_ltm                            0
number_of_reviews_l30d                           0
number_of_reviews_ly                             0
estimated_occupancy_l365d                        0
first_review                                    58
last_review                                     58
review_scores_accuracy                          58
review_scores_cleanliness                       58
review_scores_checkin                           58
review_scores_communication                     58
review_scores_location                          58
review_scores_value                             58
calculated_host_listings_count                   0
calculated_host_listings_count_entire_homes      0
calculated_host_listings_count_private_rooms     0
calculated_host_listings_count_shared_rooms      0
reviews_per_month                               58
avg_rating_score                                58
hosts_time_as_host_total_years                   0
hosts_time_as_user_total_years                   0
bathrooms_shared                                 0
dtype: int64

In [932]:
df['avg_rating_score'].fillna(np.nan,inplace=True)

/var/folders/bd/mlt6cbds60dbx8t8hmpk2xtw0000gp/T/ipykernel_34888/3978154681.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['avg_rating_score'].fillna(np.nan,inplace=True)

In [933]:
df['calendar_last_scraped'].value_counts()
df = df.drop(columns=['last_scraped','calendar_last_scraped']) #All values same

In [934]:
df['calculated_host_listings_count_shared_rooms'].value_counts()
df = df.drop(columns='calculated_host_listings_count_shared_rooms') #All values 0

In [935]:
df['host_listings_count'].equals(df['calculated_host_listings_count'])

False

In [936]:
df = df.drop(columns='host_listings_count')

In [937]:
df = df.drop(columns=['number_of_reviews_ltm','number_of_reviews_l30d','number_of_reviews_ly'])

In [938]:
df = df.drop(columns=['review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value'])

In [939]:
df = df.drop(columns='reviews_per_month')

In [940]:
df = df.drop(columns='source')

In [941]:
df = df.drop(columns=['calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms'])

In [942]:
df = df.drop(columns=['name','description','amenities'])

In [943]:
df['first_review'] = pd.to_datetime(df['first_review'],errors='coerce')
df['last_review'] = pd.to_datetime(df['last_review'],errors='coerce')

In [944]:
df['review_span'] = df['last_review'] - df['first_review']
df['review_span']

0     2969 days
1     4181 days
2     3927 days
3           NaT
4     3676 days
         ...
448         NaT
449         NaT
450         NaT
451         NaT
452         NaT
Name: review_span, Length: 453, dtype: timedelta64[ns]

In [945]:
df = df.drop(columns=['first_review','last_review'])

In [946]:
num_cols = df.select_dtypes(include=['int64','float64']).columns
num_cols

Index(['id', 'host_id', 'latitude', 'longitude', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'minimum_nights', 'maximum_nights',
       'availability_365', 'number_of_reviews', 'estimated_occupancy_l365d',
       'calculated_host_listings_count', 'avg_rating_score',
       'hosts_time_as_host_total_years', 'hosts_time_as_user_total_years',
       'bathrooms_shared'],
      dtype='object')

In [947]:
numerical_cols = ['accommodates','bathrooms','bedrooms','beds','minimum_nights', 'maximum_nights',
       'availability_365', 'number_of_reviews', 'estimated_occupancy_l365d',
       'calculated_host_listings_count', 'avg_rating_score',
       'hosts_time_as_host_total_years', 'hosts_time_as_user_total_years']

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_fence = Q1 - 1.5*IQR
    upper_fence = Q3 + 1.5*IQR
    outliers = df[(df[col] < lower_fence) | (df[col] > upper_fence)]
    print(col,outliers.shape[0])

accommodates 35
bathrooms 97
bedrooms 30
beds 45
minimum_nights 81
maximum_nights 0
availability_365 0
number_of_reviews 45
estimated_occupancy_l365d 0
calculated_host_listings_count 30
avg_rating_score 32
hosts_time_as_host_total_years 0
hosts_time_as_user_total_years 0

In [948]:
df.columns

Index(['id', 'host_id', 'host_name', 'host_location', 'host_is_superhost',
       'host_identity_verified', 'neighbourhood_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bedrooms', 'beds', 'minimum_nights', 'maximum_nights',
       'availability_365', 'number_of_reviews', 'estimated_occupancy_l365d',
       'calculated_host_listings_count', 'avg_rating_score',
       'hosts_time_as_host_total_years', 'hosts_time_as_user_total_years',
       'bathrooms_shared', 'review_span'],
      dtype='object')